name: CD

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    permissions:
      contents: write
    uses: jeffersonlab/java-workflows/.github/workflows/gh-release.yaml@v2
    with:
      files: build/libs/weather.war
    secrets: inherit

  acctest_deploy:
    permissions:
      contents: read
    needs:
      - release
    uses: jeffersonlab/general-workflows/.github/workflows/jlab-deploy-app.yaml@v2
    with:
      app: weather
      env: acctest
      ver: ${{ needs.release.outputs.semver }}
    secrets: inherit